package net.coobird.thumbnailator.events;

import java.awt.image.BufferedImage;
import java.io.File;

import net.coobird.thumbnailator.tasks.ThumbnailTask;

/**
 * An abstract adapter class for receiving events generated by Thumbnailator.
 * <p>
 * The implementation of each class is empty.
 * 
 * @author coobird
 *
 */
public abstract class ThumbnailatorEventAdapter 
		implements ThumbnailatorEventListener
{
	public void processedBufferedImage(BufferedImage sourceImage,
			BufferedImage destinationImage) {}

	public void processedFile(File sourceFile, File destinationFile) {}

	public void processedTask(ThumbnailTask task) {}
	
	public void progressFile(ThumbnailatorEvent event, File sourceFile) {}

	public void progressTask(ThumbnailatorEvent event, ThumbnailTask task) {}

	public void beginBufferedImage(BufferedImage sourceImage) {}

	public void beginFile(File sourceFile) {}

	public void beginTask(ThumbnailTask task) {}
}
