package net.coobird.thumbnailator.events;


/**
 * An abstract adapter class for receiving events generated by Thumbnailator.
 * <p>
 * The implementation of each class is empty.
 * 
 * @author coobird
 *
 */
public abstract class ThumbnailatorEventAdapter 
		implements ThumbnailatorEventListener
{
	public void beginProcessing(Object source) {}
	
	public void failedProcessing(ThumbnailatorEvent event, Object source) {}
	
	public void processing(ThumbnailatorEvent event, Object source) {}
	
	public void finishedProcessing(Object source, Object destination) {}
}
